# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 18:51
from __future__ import unicode_literals

from django.db import migrations

def correct_descriptions(apps, schema_editor):
    """
    I made a mistake with Infection's description...again...
    :param apps:
    :param schema_editor:
    :return:
    """
    Project = apps.get_model("projects", "Project")
    infection = Project.objects.get(title="Infection")
    infection.description = \
    """
    A Khan Academy project written in C++ (with visual components relying on the SFML library) designed to simulate the needs for teacher/students pairs to be able to work on the same type of software regardless of who is teaching who. That is, a teacher can teach a student who in turn could also potentially teach someone else, or the original teacher.
    """
    infection.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20151219_1839'),
    ]

    operations = [
        migrations.RunPython(correct_descriptions),
    ]
