# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 15:15
from __future__ import unicode_literals

from django.db import migrations


def import_categories(apps, schema_editor):
    """

    :param apps:
    :param schema_editor:
    :return:
    """
    PostCategory = apps.get_model("blog", "PostCategory")
    PostCategory(name="default", img_src="default-icon.png").save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postcategory'),
    ]

    operations = [
        migrations.RunPython(import_categories),
    ]
