# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 15:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20151222_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img_src',
        ),
        migrations.AddField(
            model_name='post',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.PostCategory'),
        ),
        migrations.AddField(
            model_name='post',
            name='last_modified',
            field=models.DateField(auto_now=True, default=datetime.datetime(2015, 12, 22, 15, 19, 54, 230682)),
            preserve_default=False,
        ),
    ]
