# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='content_url',
            field=models.URLField(default='/blog/entries/2015/December/22_1.html', max_length=255),
            preserve_default=False,
        ),
    ]
