# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 02:11
from __future__ import unicode_literals

from django.db import migrations


def import_post(apps, schema_editor):
    """

    :param apps:
    :param schema_editor:
    :return:
    """
    Post = apps.get_model("blog", "Post")
    PostCategory = apps.get_model("blog", "PostCategory")
    Post(title="First Post", category=PostCategory.objects.get(name="default"), description='The following will be my first blog post detailing what I expect to eventually do with this site. In particular, I discuss the distinction between the "blog" and "research" tab, how I envision the site to look as the number of posts/projects grow, etc.', content_url='blog/entries/2015/December/22_1.html').save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20151223_0049'),
    ]

    operations = [
        migrations.RunPython(import_post),
    ]
