# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 03:21
from __future__ import unicode_literals

from django.db import migrations


def revise_categories(apps, schema_editor):
    """

    :param apps:
    :param schema_editor:
    :return:
    """
    PostCategory = apps.get_model("blog", "PostCategory")
    PostCategory(name='math', img_src='math.png').save()
    default = PostCategory.objects.get(name='default')
    default.name = 'admin'
    default.img_src = 'admin.png'
    default.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20151223_0215'),
    ]

    operations = [
        migrations.RunPython(revise_categories),
    ]
