# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 00:51
from __future__ import unicode_literals

from django.db import migrations


def import_post(apps, schema_editor):
    """

    :param apps:
    :param schema_editor:
    :return:
    """
    Post = apps.get_model("blog", "Post")
    PostCategory = apps.get_model("blog", "PostCategory")
    Post(title="Wikipedia Page", category=PostCategory.objects.get(name="admin"), description="A very quick update on the status of the site and the new Wikipedia endpoint.", content_url="blog/entries/2015/December/28_1.html").save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20151227_0321'),
    ]

    operations = [
        migrations.RunPython(import_post),
    ]
