# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 19:45
from __future__ import unicode_literals

from django.db import migrations


def import_post(apps, schema_editor):
    """

    :param apps:
    :param schema_editor:
    :return:
    """
    Post = apps.get_model("blog", "Post")
    PostCategory = apps.get_model("blog", "PostCategory")
    Post(title="Transformations", category=PostCategory.objects.get(name="math"), description="Post involving an in depth understanding of the Fourier Transform, with the Jacobian as a primer. I end with a discussion on the use of DCT (a close cousin to the Fourier Transform) and how it is used in JPEG compression.", content_url="blog/entries/2015/December/30_1.html").save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20151229_0051'),
    ]

    operations = [
        migrations.RunPython(import_post),
    ]
