# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20151231_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_src',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
