# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 22:06
from __future__ import unicode_literals

from django.db import migrations


def add_category(apps, schema_editor):
    """

    :param apps:
    :param schema_editor:
    :return:
    """
    PostCategory = apps.get_model("blog", "PostCategory")
    PostCategory(name='personal', img_src='personal-icon.png').save()


def import_post(apps, schema_editor):
    """

    :param apps:
    :param schema_editor:
    :return:
    """
    Post = apps.get_model("blog", "Post")
    PostCategory = apps.get_model("blog", "PostCategory")
    Post(title="Vandwelling Life", category=PostCategory.objects.get(name="personal"), description="Why I'm deciding to live in a van, for at least a bit of time.", content_url="blog/entries/2016/March/13_1.html").save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_img_src'),
    ]

    operations = [
        migrations.RunPython(add_category),
        migrations.RunPython(import_post),
    ]
