# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-01 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20160313_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_added',
            field=models.DateField(),
        ),
    ]
