# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-01 04:25
from __future__ import unicode_literals

from django.db import migrations
from datetime import datetime


def update_posts(apps, schema_editor):
    """

    :param apps:
    :param schema_editor:
    :return:
    """
    Post = apps.get_model("blog", "Post")

    p = Post.objects.get(title="First Post")
    p.date_added = datetime(2015, 12, 23)
    p.content_url = '2015/December/22_1.html'
    p.save()

    p = Post.objects.get(title="Wikipedia Page")
    p.date_added = datetime(2015, 12, 29)
    p.img_src = 'wikipedia.png'
    p.content_url = '2015/December/28_1.html'
    p.save()

    p = Post.objects.get(title="Fourier Transform")
    p.date_added = datetime(2015, 12, 31)
    p.content_url = '2015/December/30_1.html'
    p.save()

    p = Post.objects.get(title="Vandwelling Life")
    p.date_added = datetime(2016, 5, 1)
    p.content_url = '2016/May/1_1.html'
    p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_postcategory_img_src'),
    ]

    operations = [
        migrations.RunPython(update_posts),
    ]
