# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 23:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='content_url',
            field=models.URLField(default='research/entries/default.html', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='research',
            name='last_modified',
            field=models.DateField(auto_now=True, default=datetime.datetime(2015, 12, 25, 23, 42, 4, 15476)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='research',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='img_src',
            field=models.URLField(max_length=255),
        ),
    ]
