# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 23:42
from __future__ import unicode_literals

from django.db import migrations


def import_post(apps, schema_editor):
    """

    :param apps:
    :param schema_editor:
    :return:
    """
    Research = apps.get_model("research", "Research")
    Research(title="Transformations", img_src="research/imgs/transformations.png", description='The following post details my understanding of transformations and how they are useful in everday contexts. In particular, I discuss the Jacobian as a primer before tackling the Fourier Transform (and the FFT variant).', content_url='research/entries/2015/December/25_1.html').save()


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20151225_2342'),
    ]

    operations = [
        migrations.RunPython(import_post),
    ]
